### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by wintan1418**
This is my first PR on the third milestone project, not yet perfect, but to submit the applied methods, and get more directions from reviews

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @wintan1418 and @KinezaEnaelle 

You've done a good job so far but there are a few changes you need to effect before this milestone can be approved. See them below:

## REQUIRED

* [ ] Fix linter errors
* [ ] No `puts/print` and `gets.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] You're to use attr_readers/attr_writers. Only use attr_accessors if you really need it and you must be aware that by using it you allow writing that property from outside the class. That variable can be set to anything. <TODO: explain why> ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))
* [ ] Your application allows both players to select the same piece.
image
- [ ] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

##### Behaviour

* [ ] The application does not allow a player to move into an occupied position
* [ ] The application does not exit/stop due to invalid input - it informs the player about it and asks for their move again
* [ ] The application saves players move and displays status of the board after that.
* [ ] The application can determine if the move is a winning move
  * [ ] The application can detect a sequence of three horizontal elements that are equal
  * [ ] The application can detect a sequence of three vertical elements that are equal
  * [ ] The application can detect a sequence of three equal elements in a diagonal from left and right to right
* [ ] The application can tell if there was a draw after players move
* [ ] The application can change active player

### Make the required changes and submit for another review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
### Hi @wintan1418 and @KinezaEnaelle ! 👋 

#### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**

- [ ] Fix your rubocop errors.

- [ ] No puts/print and gets.chomp outside main.rb file. 

- [ ] You have multiple lines of commented out code in your `main.rb` file, please remove it.

- [ ] The application can determine if the move is a winning move: 
   -  The application can detect a sequence of three horizontal elements that are equal
   - The application can detect a sequence of three vertical elements that are equal
   - The application can detect a sequence of three equal elements in a diagonal from left and right to right.

- [ ] Both players should either be 'x' or 'o' currently, both are being saved as 'x' hereby making it hard for the game to compute whether it's a win or a draw.

- [ ] Currently, your game is never-ending and continuously asks only the first player to input a value, even though the entire board space is filled. See below:

Screenshot (129)





__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello @wintan1418  and @KinezaEnaelle :wave: 
Well done for the work you have done so far.
Some part of your logic seems broken, check below for changes that you need to make
- [ ] There should be no puts or chomp outside main.rb. So update your code to move all puts and chomp to the main.rb file.
- [ ] Currently, your game is not able to change between active players. This causes the same player to be called each time the game needs to taken input from a player and consequently this faults the logic and flow of the game. Please make an update accordingly.
Screenshot from 2020-12-10 18-01-12

Request another review when you are done making the changes

slack(@ebeagusamuel)

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🤓 

## Hello team 😄,

**Great job implementing the requested changes. However, there are still a few fixes needed.**

1). **Fix the `rubocop` offences seen below.**
rspec

2). **When asked to enter the name of the player, the game accepts a blank value as a name, as shown in the screenshot below. Please fix that.**

blank

3). **Some of your winning moves are not being detected. An example is shown in the screenshot below, the game is not terminated yet there is a winning sequence. Please counter check all your winning moves because this is not the only one.**
win

4). **The following screenshot shows the game is drawn yet there is a win.**

draw_win

5). **If I press `enter` key as an invalid move, the game is terminated instead of getting a message of an invalid move. Please fix that.**

6). **As mentioned by the previous TSE, there should be no puts outside `main.rb`. Your `game.rb` and `board.rb` have used `puts`. Please remove them all.**

## [Optional]

- For this message `Enter y to play again or n to quit` when I enter `y` the game pick quit option.

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes  ♲
Hi @wintan1418, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏 You did very well on this project. Most requirements have done 👌, Kindly fix the following issues.

[Required]

- [ ] Don't use console input-output such as `print`, `puts`, `gets` methods outside the main file.
- [ ] remove inline comments, instead use descriptive names
- [ ] Remove the .gitkeep since the folders are not empty.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by Srjnnnn — APPROVED** [review]
## Status Approved :partying_face: :tada: 
Hello @wintan1418 @KinezaEnaelle. Thanks for making the requested changes. Your game is just great. :muscle: It has all the behavioral and implementation features that it needs to have.

### Optional
- [ ]  You can add a re-play option after the game ends.
- [ ] I believe after pressing the enter there is no need to ask that do you want to play. You can delete this logic from your game.

Again, it is an excellent work and congratulations. You can do the optional changes if you feel like and you can merge and move on.
_Eyüp Sercan UYGUR_

**Pull request merged**
